name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build --if-present
        # If necessary, try: ng build --configuration production

      - name: List built artifacts
        run: ls -la dist
        # This step helps confirm which folder(s) were generated.

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages           # The branch the action should deploy to.
          folder: dist/angular-option-list  # Adjust this if your build outputs to a different folder.
